[API] 通知周りの不具合修正
saitamau-maximum/meline pull request #113
Opened 2024-11-23 14:13 UTC by Daaaai0809

- 自分自身に通知が飛んでいたのを直した
- チャンネルに参加していないユーザにも通知が飛んでいたのでこれを修正

2024-11-24 01:53 UTC, sor4chi requested changes
色々な修正を一つのコミットでまとめてやってたりしてレビューむずかった

作業ログじゃなくて機能単位で切って欲しいな
「[API] 通知周りの不具合修正」が何の修正何か知りたいっすね

2024-11-24 01:53 UTC, sor4chi commented on docker-compose.yml
> -version: "3"
https://zenn.dev/harpseal/articles/8dc2602ffe3365
これ消して良くなったんか

2024-11-24 01:53 UTC, sor4chi commented on server/adapter/handler/message_handler.go
> +	h.hub.NotifyBroadcastCh <- entity.NewNotifyBroadcastChEntity(jsonNotifyRes, userId, userIDs, channelIdUint64)
imo: userIdとuserIdっていう変数名がわかりづらいかも
userIdはもうすでにコンテキストでそう定義されてるからいいけど、userIdsはchannelUserIdsみたいな命名の方がわかりやすいかもと思った

今回の変更内容じゃないけどすまん

2024-11-24 01:53 UTC, sor4chi commented on server/adapter/handler/message_handler.go
> +	h.hub.NotifyBroadcastCh <- entity.NewNotifyBroadcastChEntity(jsonNotifyRes, userId, userIDs, channelIdUint64)
ハンガリアン記法 (変数名に型情報をつける) のはやめたい
parsedChannelIdにするかもしくはparse前のやつを_channelIdにすると良さそう

これも今回の変更じゃないけど

2024-11-24 01:53 UTC, sor4chi commented on server/adapter/handler/websocket_handler.go
> +		return h.messageClientInteractor.ReadPump(ctx, client, h.hub)
これリファクタのコミット（一つか二つ前？）に含めるべきじゃない？
コミットはビルドが通る単位で切った方がいいともうよ

2024-11-24 01:53 UTC, sor4chi commented on server/domain/entity/notify_clinet_joined_channel.go
> +	IsNotify bool // 将来的に通知の有無を設定できるようにする
変数名になんか違和感がある
enableNotificationとかshouldNotifyのほうがいいかも。
is prefixにしたいなら isNotificationEnabledとか？

2024-11-24 01:53 UTC, sor4chi commented on server/domain/entity/notify_client.go
> +	JoinedChannelIDs map[uint64]*NotifyClientJoinedChannel
q: これ変数的に配列に見えるけどもっといい名ないだろうか

2024-11-24 01:53 UTC, sor4chi commented on server/domain/entity/notify_clinet_joined_channel.go
> +	IsNotify bool // 将来的に通知の有無を設定できるようにする
というかそもそも将来的な機能はその時作ればいいので空のstructでいい気がする

2024-11-24 01:53 UTC, sor4chi commented on server/adapter/handler/websocket_handler.go
> +	client := entity.NewNotifyClientEntity(conn, userId, joinedChannels)
handlerにビジネスロジックを書くのにすごい違和感がある

2024-11-24 01:53 UTC, sor4chi commented on server/adapter/handler/websocket_handler.go
> +	client := entity.NewNotifyClientEntity(conn, userId, joinedChannels)
あと/notifyってチャンネル通知しかないの？

2024-11-24 01:53 UTC, sor4chi commented on server/adapter/handler/websocket_handler.go
> +	client := entity.NewNotifyClientEntity(conn, userId, joinedChannels)
notify_interactor的なやつなかったっけ？
notifyInteractor.CreateNotifyClient(conn, userId, joinedChannels)的な？

2024-11-24 01:53 UTC, sor4chi commented on server/domain/entity/notify_clinet_joined_channel.go
> +	IsNotify bool // 将来的に通知の有無を設定できるようにする
てかこのentityいる？通知したくなければNewNotifyClientEntityに渡すmapに含めなければいいだけな気がする

2024-11-24 01:53 UTC, sor4chi commented on server/usecase/channel_interactor.go
> +func (i *ChannelInteractor) GetJoinedChannelIDs(ctx context.Context, userID uint64) ([]uint64, error) {
これはnotifyロジックをinteracterに移せばそっち側でchannelRepository呼べばいいからいらなくなりそう

2024-11-24 01:53 UTC, sor4chi commented on server/domain/entity/hub.go
> +func (h *Hub) NotifyBroadcastMessage(message []byte, senderID uint64, userIDs []uint64, channelID uint64) {
そもそもこの関数の内部でチャンネルjoin判定しなくてもこの関数の外部で送信先をフィルタしてから引数に渡すみたいな感じじゃダメなの...？

関数名も相まってより暗黙的な操作になってそう

2024-11-24 01:53 UTC, sor4chi commented on server/domain/entity/hub.go
> +}
これはentityのフィールド関数にしなくていいんかな？

2024-11-24 05:23 UTC, Daaaai0809 commented on docker-compose.yml
> -version: "3"
こいつのせいでapacheに`localhost:80`乗っ取られてクソ困惑してた

2024-11-24 05:24 UTC, Daaaai0809 commented on server/adapter/handler/message_handler.go
> +	h.hub.NotifyBroadcastCh <- entity.NewNotifyBroadcastChEntity(jsonNotifyRes, userId, userIDs, channelIdUint64)
確かに

2024-11-24 05:25 UTC, Daaaai0809 commented on server/adapter/handler/websocket_handler.go
> +		return h.messageClientInteractor.ReadPump(ctx, client, h.hub)
それな、今気づいた

2024-11-24 05:28 UTC, Daaaai0809 commented on server/domain/entity/notify_clinet_joined_channel.go
> +	IsNotify bool // 将来的に通知の有無を設定できるようにする
これただ単に`Join/Leave`の時のロジックを簡単にしたかっただけで作った
`Leave`の時にfor文で退出したチャンネルのID探すくらいならmapでチャンネルの設定なりをあらかじめ`NotifyClient`に持たせておいて探索する方が実装的にも楽かなって

2024-11-24 05:28 UTC, Daaaai0809 commented on server/domain/entity/notify_client.go
> +	JoinedChannelIDs map[uint64]*NotifyClientJoinedChannel
そのまんまだけど`JoinedChannelMap`とか？

2024-11-24 05:31 UTC, Daaaai0809 commented on server/adapter/handler/websocket_handler.go
> +	client := entity.NewNotifyClientEntity(conn, userId, joinedChannels)
> handlerにビジネスロジックを書くのにすごい違和感がある
interactorにまとめた方がいいなこれ

> あと/notifyってチャンネル通知しかないの？
今のところそれしかない

> notify_interactor的なやつなかったっけ？
`notify_client_interactor`ってのがあるから書くならそこやな

2024-11-25 01:45 UTC, sor4chi commented on server/adapter/handler/websocket_handler.go
> +	client := entity.NewNotifyClientEntity(conn, userId, joinedChannels)
```suggestion
	client := entity.NewNotifyClientEntity(conn, userId, joinedChannelIDs)
```

にしてNotifyClientJoinedChannelはここで生成する必要がなさそう

2024-11-25 08:01 UTC, sor4chi approved these changes
よくなってそう、ありがとう

2024-11-25 08:01 UTC, sor4chi commented on server/domain/entity/hub.go
ここら辺のビジネスロジックってテスト書いてないんだっけ？

2024-11-25 08:03 UTC, Daaaai0809 commented on server/domain/entity/hub.go
ここらは書いてないね
WebSocket周りのテストってどないしたらいいのかあんま分からんから後々調べてやろうって魂胆なり

2024-11-25 08:06 UTC, merged