feat: 認証機構
saitamau-maximum/meline pull request #23
Opened 2023-11-10 19:33 UTC by Daaaai0809

2023-11-11 03:40 UTC, sor4chi requested changes

2023-11-11 03:40 UTC, sor4chi commented on server/controller/handler/auth_handler.go
> +}
GatewayやHandlerはインターフェースで抽象化する必要ないと思うんだけどどう思う？

2023-11-11 03:40 UTC, sor4chi commented on server/controller/gateway/auth_gateway.go
> +}
GatewayやHandlerはインターフェースで抽象化する必要ないと思うんだけどどう思う？

2023-11-11 03:40 UTC, sor4chi commented on server/infra/auth/auth_repository.go
> +}
`NewGithubOAuthConf()`が頻出してるけど、これこそ`type AuthRepository`のフィールドから渡せば綺麗に共通化できそう

2023-11-11 03:40 UTC, sor4chi commented on server/infra/auth/auth_repository.go
> +func (r *AuthRepository) GetGithubUser(ctx context.Context, token string) ([]byte, error) {
`GetGithubUser`の中で`json.Marshal`してstringでreturnした方が良くない？

2023-11-11 03:40 UTC, sor4chi commented on server/infra/auth/auth_repository.go
> +	return token.SignedString([]byte(os.Getenv("JWT_SECRET")))
これ`JWT_SECRET`が空だった時、空文字シークレットでtokenが生成されて、セキュリティ的に問題になりそう
そもそも存在しなかったらプロセスを落とすくらいの強気でいいと思う

2023-11-11 03:40 UTC, sor4chi commented on server/infra/auth/auth_repository.go
> +func (r *AuthRepository) CreateAccessToken(ctx context.Context, user *entity.User) (string, error) {
```suggestion
func (r *AuthRepository) GenerateAccessToken(ctx context.Context, user *entity.User) (string, error) {
```

2023-11-11 03:40 UTC, sor4chi commented on server/usecase/auth_interactor.go
ビジネスロジックがないならinteractorいらなくない？ただの二重管理になってる気がする

2023-11-11 03:40 UTC, sor4chi commented on server/usecase/auth_interactor.go
handlerからrepository直接叩くのは依存の方向的に正しいから大丈夫なはず

2023-11-11 03:40 UTC, sor4chi commented on server/models/user.go
> +	GithubID string `bun:"github_id,pk,notnull"`
これなぜ？pk2こあるくね

2023-11-11 03:40 UTC, sor4chi commented on server/domain/repository/auth_repository.go
> +	CreateAccessToken(ctx context.Context, user *entity.User) (string, error)
`CreateAccessToken`、リポジトリ化する必要なくない？どこの外部infraにも依存してないよね？
普通に`authInteractor`に書けばいいと思う

2023-11-11 03:40 UTC, sor4chi commented on server/utils/gen_state.go
ファイル名変えたい
`secure`や`secret`なんてどう

2023-11-11 03:40 UTC, sor4chi commented on server/usecase/user_interactor.go
> +	repository repository.IUserRepository
`userRepository`に命名変えよう

2023-11-11 03:40 UTC, sor4chi commented on server/usecase/user_interactor.go
> +}
このメソッドもrepository直接叩けばいいからいらないと思う
複雑なビジネスロジック必要ならいいけども

2023-11-11 03:40 UTC, sor4chi commented on server/infra/mysql/user_repository.go
> +	}
単純な1インサートでトランザクションいる？

2023-11-11 03:40 UTC, sor4chi commented on server/controller/handler/auth_handler.go
> +	githubId := res["login"].(string)
`login`しか取らないの？
`res`の中に`github_id`とか入ってたりしないか？

2023-11-11 07:57 UTC, Daaaai0809 commented on server/controller/handler/auth_handler.go
> +	githubId := res["login"].(string)
loginがgithub_idだよ

2023-11-11 09:45 UTC, Daaaai0809 commented on server/utils/gen_state.go
OAuthで使う`state`の生成にしか使わんし関数名を`GenerateState`にする方がいいと思うます

2023-11-11 11:02 UTC, Daaaai0809 commented on server/controller/gateway/auth_gateway.go
> +}
Gateway, Handlerの役割とか責務を明確にできるし抽象化してもいいと思う

2023-11-11 11:02 UTC, Daaaai0809 commented on server/controller/handler/auth_handler.go
> +}
Gateway, Handlerの役割とか責務を明確にできるし抽象化してもいいと思う

2023-11-11 12:40 UTC, sor4chi commented on server/controller/handler/auth_handler.go
> +}
え、handlerとかmockすることある？

2023-11-11 12:41 UTC, sor4chi commented on server/utils/gen_state.go
〜にしか使わないからという理由で汎用性のあるものを共通化するためにおくutilにスコープが限られたものを置くのは違うと思うけどな

2023-11-11 12:44 UTC, sor4chi commented on server/controller/handler/auth_handler.go
> +	githubId := res["login"].(string)
この後`GetUserByGithubID`を叩いてるけどそれしなくてもresから取れない？っていう話

2023-11-11 12:44 UTC, sor4chi commented on server/controller/gateway/auth_gateway.go
> +}
え、gatewayとかmockすることある？

2023-11-11 12:58 UTC, sor4chi commented
DockerComposeのprodが動かない、buildが.になってるっぽい
修正できる＞

2023-11-12 05:58 UTC, Daaaai0809 commented on server/controller/gateway/auth_gateway.go
> +}
ないな、やっぱせんでええわ

2023-11-12 05:59 UTC, Daaaai0809 commented on server/utils/gen_state.go
あーそれは確かに.
utilsではないな

2023-11-12 06:24 UTC, Daaaai0809 commented
> DockerComposeのprodが動かない、buildが.になってるっぽい 修正できる？

`COPY --from=builder /app/sql /app/sql`でnot foundなるけどこれは消していいやつ？？

2023-11-12 15:13 UTC, sor4chi requested changes

2023-11-12 15:13 UTC, sor4chi commented on server/controller/gateway/auth_gateway.go
> +		})
JWT_SECRETがない時Unauthorizedが返ることになってる

os.Exitするのがいいと思う
internalServerError返すとユーザー側にJWT_SECRET is not setが露出する

2023-11-12 15:13 UTC, sor4chi commented on server/controller/handler/auth_handler.go
> +}
authグループを`NewAuthHandler`に渡すんじゃないの？

2023-11-12 15:13 UTC, sor4chi commented on server/usecase/user_interactor.go
> +func (i *UserInteractor) CreateUserAndGetByGithubID(ctx context.Context, githubID, name, imageURL string) (*entity.User, error) {
```suggestion
func (i *UserInteractor) CreateUser(ctx context.Context, githubID, name, imageURL string) (*entity.User, error) {
```

これは普通にCreateUserでいい気がするな

2023-11-12 15:13 UTC, sor4chi commented on server/domain/repository/auth_repository.go
> +	GetGithubUser(ctx context.Context, token string) (map[string]interface{}, error)
```suggestion
	GetOAuthURL(ctx context.Context, state string) string
	GetOAuthToken(ctx context.Context, code string) (string, error)
	GetOAuthUser(ctx context.Context, token string) (map[string]interface{}, error)
```

関数名からGithubけしたいんだけどどう？
この方がたとえば後でTwitterとかの認証が増えた時にも対応できると思うんだけど

2023-11-12 15:13 UTC, sor4chi commented on server/models/user.go
> +	ImageURL string `bun:"image_url"`
これはnotnull無理なんだっけ

2023-11-12 15:13 UTC, sor4chi commented on server/migrations/20231028100209_create_user_table.go
SQLに管理変える件どうなった？

2023-11-12 16:29 UTC, Daaaai0809 commented on server/controller/handler/auth_handler.go
> +}
apiGroup渡して`NewAuthHandler`でauthGroup作るで良くない？
他でauthGroup使うことありそうなら`server/main.go`で作って渡した方がいいかもだけど

2023-11-12 16:32 UTC, Daaaai0809 commented on server/migrations/20231028100209_create_user_table.go
それって別でissue切るって話じゃなかった？？

2023-11-12 16:33 UTC, sor4chi commented on server/migrations/20231028100209_create_user_table.go
切られてなくね？

2023-11-12 16:34 UTC, Daaaai0809 commented on server/migrations/20231028100209_create_user_table.go
あーまだ切ってないや
やっとくー

2023-11-12 22:21 UTC, sor4chi commented on server/controller/handler/auth_handler.go
> +}
えー、`/api`以下を全て登録可能な状態で渡すと意図的にgroupで分けてる意味なくない？
このサブパスに今ハンドラ群を登録っていうのが`server/main.go`で一元的にみれた方が圧倒的にいいと思うな

`apiGroup`渡すならまだecho.Context渡した方がいい

2023-11-13 03:28 UTC, Daaaai0809 commented on server/domain/repository/auth_repository.go
> +	GetGithubUser(ctx context.Context, token string) (map[string]interface{}, error)
いまいちイメージがわかないんだけど、Twitterとかの認証増えた場合って同じrepositoryで実装するの？？
GithubとTwitterで分けるんじゃなくて？？

2023-11-13 03:29 UTC, Daaaai0809 commented on server/controller/handler/auth_handler.go
> +}
> /api以下を全て登録可能な状態で渡すと意図的にgroupで分けてる意味なくない？

腑に落ちた。おけまる

2023-11-13 04:42 UTC, sor4chi commented on server/domain/repository/auth_repository.go
> +	GetGithubUser(ctx context.Context, token string) (map[string]interface{}, error)
うん、俺のイメージ的にはOAuthProviderっていう外部レイヤーのイメージだったけどな
ドメイン内のリポジトリに外部の名前入るの気持ち悪くない？

2023-11-13 04:51 UTC, Daaaai0809 commented on server/domain/repository/auth_repository.go
> +	GetGithubUser(ctx context.Context, token string) (map[string]interface{}, error)
あーなんとなくだけどイメージ沸いた
あと、ドメイン内に外部の名前があるのは確かにきもいな

2023-11-13 05:35 UTC, sor4chi commented on server/domain/repository/auth_repository.go
> +	GetGithubUser(ctx context.Context, token string) (map[string]interface{}, error)
方針は自分が提案しているものでなくてもいいけど、とりあえずGithubっていう名前を含めたくないなっていう
それでいうと`map[string]interface{}`もgithubフィールドのものになっているから`OAuthUserResponse`みたいなstructで共通化してから返した方がいいかも

2023-11-15 05:54 UTC, Daaaai0809 commented on server/domain/repository/auth_repository.go
> +	GetGithubUser(ctx context.Context, token string) (map[string]interface{}, error)
んー、一瞬気持ち悪いかなと思ったけどそうでもなくなってきた
```
domain/
|-- entities/
|-- repositories/
    |-- twitter_repository_interface.go
    |-- google_repository_interface.go
    |-- github_repository_interface.go
```
俺のイメージ認証増えた時はこんな感じにすると思ってた

2023-11-15 06:37 UTC, sor4chi requested changes

2023-11-15 06:37 UTC, sor4chi commented on server/infra/github/auth_repository.go
`oauth_repository`にリネームしてほしす

2023-11-15 06:37 UTC, sor4chi commented on server/infra/github/auth_repository.go
あとAuth*関連の命名全部

2023-11-15 13:09 UTC, sor4chi requested changes

2023-11-15 13:09 UTC, sor4chi commented on server/usecase/github_oauth_interactor.go
> +	GenerateState(b int) string
b -> length

2023-11-15 13:09 UTC, sor4chi commented on server/controller/handler/oauth_handler.go
> +	b = 32
`STATE_LENGTH`

2023-11-15 14:26 UTC, sor4chi requested changes

2023-11-15 14:26 UTC, sor4chi commented on .env.example
> +# ENV="prod"
prod -> production

2023-11-15 14:26 UTC, sor4chi commented on .env.example
> +FRONT_CALLBACK_URL="http://localhost/
FRONT_CALLBACK_URL="http://localhost/"

2023-11-15 14:28 UTC, sor4chi approved these changes
お疲れ様

2023-11-15 14:28 UTC, merged