authmiddlewareでuserが存在するかの判定追加 / サーバー
saitamau-maximum/meline pull request #72
Opened 2024-04-04 05:29 UTC by Daaaai0809

2024-04-04 05:52 UTC, sor4chi requested changes

2024-04-04 05:52 UTC, sor4chi commented on server/usecase/user_interactor.go
> +	CheckExistUser(ctx context.Context, userID uint64) (bool, error)
`(bool, error)` より `(bool)` の方が良くない？

2024-04-04 05:52 UTC, sor4chi commented on server/domain/repository/user_repository.go
> +	IsExistUser(ctx context.Context, userID uint64) (bool, error)
`IsUserExists`の方が英文法的に正しくない？

2024-04-06 06:36 UTC, Daaaai0809 commented on server/domain/repository/user_repository.go
> +	IsExistUser(ctx context.Context, userID uint64) (bool, error)
英弱ばれて泣いちゃった

2024-04-06 08:37 UTC, Daaaai0809 commented on server/usecase/user_interactor.go
> +	CheckExistUser(ctx context.Context, userID uint64) (bool, error)
それだとDBエラーの場合とユーザーが存在しない場合どちらも`false`が返ってくるけど、エラーハンドリングしない感じ？

2024-04-06 08:43 UTC, Daaaai0809 commented on server/usecase/user_interactor.go
> +	CheckExistUser(ctx context.Context, userID uint64) (bool, error)
あー今の実装だと`AuthGateway.Auth`内で
```go
isExistUser, err := h.userInteractor.CheckExistUser(c.Request().Context(), uint64(userId))
if err != nil || !isExistUser {
	return c.JSON(http.StatusForbidden, err)
}
```
こうなってるからerr返しても意味ないのか

2024-04-08 08:28 UTC, sor4chi approved these changes

2024-04-08 08:28 UTC, sor4chi commented on server/adapter/gateway/auth_gateway.go
本当はここロジック変えたならテスト書いて欲しいけどいいや

2024-04-08 08:29 UTC, Daaaai0809 commented on server/adapter/gateway/auth_gateway.go
ほな後程書きます

2024-04-08 08:29 UTC, merged