fix: Broken Pipeになる問題と接続維持の修正
saitamau-maximum/meline pull request #83
Opened 2024-04-28 19:11 UTC by Daaaai0809

2024-04-29 10:10 UTC, sor4chi requested changes
てかそもそもこの機能`gorilla/websocket`にないの？いちいち各自実装してるようには思えん

2024-04-29 10:10 UTC, sor4chi commented on server/usecase/client_interactor.go
> +	maxMessageSize = 512
小さくない？

2024-04-29 10:10 UTC, sor4chi commented on server/usecase/client_interactor.go
> +	pongWait       = 60 * time.Second
長くない？

2024-04-30 02:41 UTC, Daaaai0809 commented
@sor4chi 
ping/pong frameを実装するためのメソッドとかは用意されてるけど実装は各自

2024-04-30 02:54 UTC, sor4chi requested changes

2024-04-30 02:54 UTC, sor4chi commented on server/usecase/client_interactor.go
> +	client.Ws.SetReadLimit(maxMessageSize)
レートリミットが最大メッセージ長？どゆこと？

2024-04-30 02:54 UTC, sor4chi commented on server/usecase/client_interactor.go
> +		client.Ws.SetReadDeadline(time.Now().Add(pongWait))
`client.Ws.SetReadDeadline(time.Now().Add(pongWait))`は二箇所書く必要があるの？

2024-04-30 02:54 UTC, sor4chi commented on server/usecase/client_interactor.go
> +		log.Println("pong")
なんでlog？

2024-04-30 02:54 UTC, sor4chi commented on server/usecase/client_interactor.go
> +			log.Println("ping")
なんでlog？

2024-04-30 02:56 UTC, Daaaai0809 commented on server/usecase/client_interactor.go
> +	client.Ws.SetReadLimit(maxMessageSize)
**Read**Limitやでmessageサイズの制限しとるんや

2024-04-30 02:58 UTC, Daaaai0809 commented on server/usecase/client_interactor.go
> +			log.Println("ping")
消し忘れ ^^

2024-04-30 02:59 UTC, Daaaai0809 commented on server/usecase/client_interactor.go
> +		log.Println("pong")
![image](https://github.com/saitamau-maximum/meline/assets/130345626/0d352df4-27bd-4af4-993e-2db2a12bf1c5)

2024-04-30 10:15 UTC, Daaaai0809 commented on server/usecase/client_interactor.go
> +		client.Ws.SetReadDeadline(time.Now().Add(pongWait))
https://github.com/gorilla/websocket/blob/main/examples/chat/client.go

2024-04-30 10:53 UTC, sor4chi approved these changes

2024-04-30 11:00 UTC, merged