feat: 通知用Websocketの実装
saitamau-maximum/meline pull request #84
Opened 2024-04-30 12:17 UTC by Daaaai0809

2024-05-02 23:04 UTC, sor4chi requested changes
notifyがchannel着信のAPIだけならこれでいいんだけど、チャンネルのメッセージ受信以外の土もありそうだなと思ってもっと拡張性あったほうがいいのではと思いました

2024-05-05 05:40 UTC, Daaaai0809 commented
ごめ、普通にミスってforce pushした
[bc27eb8](https://github.com/saitamau-maximum/meline/pull/84/commits/bc27eb82cb91377d8e4249ba2af817772a3622e8)までのCommitは無視して

2024-05-05 06:38 UTC, sor4chi requested changes

2024-05-05 06:38 UTC, sor4chi commented on docs/api/websocket.md
>  }
よくなったね、だけど既存のMessage Responseをフロント側でも使いまわしたいから通知だけmessageフィールドにadditionalな値があると型変わってめんどくさい気がする

この場合
```jsonc
{
    "notify_meta": {
        "type_id": 0
    },
    "payload": {
      "message": {
          "id": "c7b2e0e2-4e4e-4a7d-9a0d-6e3e8b9c5d1f",
          // ...
          "content": "test-message",
      },
      "channel_id": 1
   }
}
```

みたいにするのはどう
こうすれば他のレスポンスと同じmessage型になって扱いやすいと思うんだよね

2024-05-07 07:18 UTC, Daaaai0809 commented on docs/api/websocket.md
>  }
よさげ
こっちでいくぜ

2024-05-07 08:19 UTC, sor4chi approved these changes

2024-05-07 08:21 UTC, merged